server:
  port: 9101

spring:
  application:
    name: @pom.artifactId@

eureka:
  client:
    serviceUrl:
      #defaultZone: http://localhost:9001/eureka/
      defaultZone: http://10.1.4.130:9001/eureka/,http://10.1.4.131:9001/eureka/,http://10.1.4.132:9001/eureka/ #集群模式